apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sr.fullname" . }}-key
  labels:
    {{- include "sr.labels" . | nindent 4 }}
type: Opaque
data:
  server.key: {{ required "serverKey is required. Use --set-file serverKey=<key-file>." .Values.serverKey | b64enc | quote }}
