apiVersion: v1
kind: Service
metadata:
  name: {{ include "sr.fullname" . }}
  labels:
    {{- include "sr.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: sr
      port: {{ .Values.service.port }}
      targetPort: sr
      protocol: TCP
  selector:
    {{- include "sr.selectorLabels" . | nindent 4 }}
